package com.mixinfer.domain;

import lombok.Builder;
import lombok.Value;

/**
 * A single generation choice in an {@link LlmResponse}.
 */
@Value
@Builder
public class LlmChoice {

    /** Zero-based index of this choice. */
    int index;

    /** The message generated by the model. */
    LlmMessage message;

    /** Reason the generation stopped, e.g. "stop", "length", "tool_calls". */
    String finishReason;
}
