package com.mixinfer.domain;

import lombok.Builder;
import lombok.Value;

/**
 * Token usage for a single request/response pair.
 */
@Value
@Builder
public class LlmUsage {

    /** Number of tokens in the prompt. */
    int promptTokens;

    /** Number of tokens generated by the model. */
    int completionTokens;

    /** Sum of prompt and completion tokens. */
    int totalTokens;
}